baseurl : /homepages
# Outputting
#permalink:     pretty
permalink: /:categories/:year/:month/:day/:title/
# sitemap
jekyll-sitemap
# highlight
# pygments: true
# highlighter:rouge
# use github flavored markdown
#markdown: redcarpet2
#redcarpet:
  #extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      author: "Zhifei Ding"
      categories: "programming"
      tags: "C++"
